# Num-Ex 예제
## 배열 생성하기

### 시퀀스 데이터로부터 배열 생성

1. arr_obj = np.array(seq_data)
  - 시퀀스 데이터(리스트, 튜플 등)를 배열로 변경
2. 배열의 속성
  - dtype : 배열 요소의 데이터 타입
  - shape : 배열의 모양(차원)을 튜플로 표현

In [80]:
import numpy as np

In [81]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [82]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [83]:
a1.dtype

dtype('int32')

In [84]:
a2.dtype

dtype('float64')

In [85]:
np.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

In [86]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 범위를 지정해 배열 생성

1. arr_obj = np.arange([start, ] stop[, step])
 - start부터 stop 전까지 step만큼 더해 배열을 생성
 - start 디폴트는 0
 - step 디폴트는 1
 

2. reshape(m, n)
 - 배열의 차원 조정
 - m x n 행태로 변경
 - 데이터의 개수가 맞아야 함
 

3. arr_obj = np.linspace(start, stop[, num])
 - start부터 stop까지(포함) num개의 NumPy 배열 생성
 - num 디폴트 값은 1
 - 등간격

In [87]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [88]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [90]:
a1 = np.arange(1, 10)
a1.shape

(9,)

In [91]:
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
a2.shape

(3, 3)

In [92]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [93]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [94]:
b2 = np.arange(5)
b2.shape

(5,)

In [95]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [96]:
np.linspace(0, np.pi, 20 )

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

### 특별한 형태의 배열 생성

1. arr_zero_n = np.zeros(n)
2. arr_zero_mxn = np.zeros((m,n))
 - 원소가 0인 배열 생성
3. arr_one_n = np.ones(n)
4. arr_one_mxn = np.ones((m,n))
 - 원소가 1인 배열 생성
5. arr_I = np.eye(n)
 - n x n 단위 행렬 생성

In [97]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [98]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [99]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [100]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [101]:
print(np.zeros((3,4,3)))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [102]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###   배열의 데이터 타입 변환

1. 배열의 데이터 타입 기호
 - b : 불
 - i : 부호가 있는 정수
 - u : 부호가 없는 정수
 - f : 실수
 - c : 복소수
 - M : 날짜
 - O : 파이썬 객체
 - S 혹은 a : 바이트 배열
 - U : 유니코드
 
2. 데이터 타입의 숫자
 - 비트 수 혹은 바이트 수
 
3. 예
 - 'U8' : 8비트 유니코드
 - 'i32' : 32비트 부호 있는 정수
 
4. arr_obj = np.astype(타입)
 - 배열을 지정한 타입으로 변환

In [103]:
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [104]:
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [105]:
str_a1.dtype

dtype('<U5')

In [106]:
num_a1.dtype

dtype('float64')

In [107]:
str_a2 = np.array(['1', '3', '5', '7', '9'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 9])

In [108]:
str_a2.dtype

dtype('<U1')

In [109]:
num_a2.dtype

dtype('int32')

In [110]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_i1 = num_f1.astype(int)
num_i1

array([10, 21,  0,  4,  5])

In [111]:
num_f1.dtype

dtype('float64')

In [112]:
num_i1.dtype

dtype('int32')

### 난수 배열의 생성

1. np.random.seed(시드값)
  - 난수 생성 시드값 설정
2. rand_num = np.random.rand()
  - [0. 1) 사이의 실수 난수 생성
3. rand_num = np.random.rand([d0, d1, …, dn])
  - 지정한 차원의 배열 생성
  - [0. 1) 사이의 실수 난수로 채움
4. rand_num = np.random.randn([d0, d1, …, dn])
  - 지정한 차원의 배열 생성
  - 가우시안 표준 정규 분포를 따르는 실수 난수 채움
5. rand_num = np.random.randint([low,] high, [,size])
  - [low, high)사이의 정수 난수를 갖는 배열 생성
  - size는 배열의 크기
      - 튜플로 지정 (d0, d1, … , dn)
  - low의 디폴트 값은 0

In [113]:
np.random.rand(2,3)

array([[0.84697853, 0.62120831, 0.13627095],
       [0.7143542 , 0.89098898, 0.28272265]])

In [114]:
np.random.rand()

0.7241939749027853

In [115]:
np.random.rand(2,3,4)

array([[[0.66389939, 0.86971375, 0.69256378, 0.30837809],
        [0.73075141, 0.88533981, 0.53311934, 0.05026312],
        [0.95869949, 0.78807179, 0.60053144, 0.99877948]],

       [[0.21904366, 0.2948743 , 0.2665492 , 0.34317217],
        [0.58322219, 0.90269163, 0.2617265 , 0.51549989],
        [0.71731255, 0.88158009, 0.54465992, 0.41063703]]])

In [116]:
np.random.randint(10, size=(3, 4))

array([[8, 8, 6, 6],
       [2, 1, 1, 3],
       [2, 7, 3, 3]])

In [117]:
np.random.randint(1, 30)

22

## 배열의 연산

### 기본 연산 

In [118]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [119]:
arr1 + arr2

array([11, 22, 33, 44])

In [120]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [121]:
arr2 * 2

array([2, 4, 6, 8])

In [122]:
arr2 ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [123]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [124]:
arr1 / arr2

array([10., 10., 10., 10.])

In [125]:
arr1 / (arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [126]:
arr1 > 20

array([False, False,  True,  True])

## 배열의 인덱싱과 슬라이싱

## 배열의 인덱싱

1. 배열명[위치]
2. 배열명[[위치1, 위치2, …, 위치n]]
 - 해당 차원의 여러 원소 선택
3. 배열명[행_위치, 열_위치]
4. 배열명[ [행_위치1, 행_위치2, … , 행_위치n],
            [열_위치1, 열_위치2, … , 열_위치n]]
 - 2차원 배열의 여러 원소를 선택
5. 배열명[조건식]
 - 해당 조건식을 만족하는 원소만 선택된 배열

In [127]:
a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [128]:
a1[0]

0

In [129]:
a1[4]

40

In [130]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [131]:
a1[[1,3,4]]

array([10, 30, 40])

In [132]:
a2 = np.arange(10, 100, 10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [133]:
a2[0, 2]

30

In [134]:
a2[2, 2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [135]:
a2[1]

array([40, 50, 60])

In [136]:
a2[1] = np.array([45, 55, 65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [137]:
a2[1] = [47, 57, 67]
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [138]:
a2[[0, 2], [0, 1]]

array([10, 80])

In [139]:
a = np.array([1, 2, 3, 4, 5, 6])
a[a > 3]

array([4, 5, 6])

In [140]:
a[(a % 2) == 0]

array([2, 4, 6])

### 배열의 슬라이싱

1. 배열[시작_위치:끝_위치]
 - 시작_위치 ~ 끝_위치-1 범위의 슬라이싱
 - 시작_위치 생략시 0
 - 끝_위치 생략시 배열의 끝

2. 배열[행시작_위치:행끝_위치, 열시작_위치:열끝_위치]
 - 2차원의 슬라이싱

In [141]:
b1 = np.array([0, 10, 20, 30, 40, 50])
b1[1:4]

array([10, 20, 30])

In [142]:
b1[:3]

array([ 0, 10, 20])

In [143]:
b1[2:]

array([20, 30, 40, 50])

In [144]:
b1[2:5] = np.array([25, 35, 45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [145]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

In [146]:
b2 = np.arange(10, 100, 10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [147]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [148]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [149]:
b2[1][0:2]

array([40, 50])

In [150]:
b2[0:2, 1:3] = np.array([[25, 35], [55, 65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])